export const SORT_TYPES = [
  { label: 'Price: Low to High', value: 'price_low_to_high' },
  { label: 'Price: High to Low', value: 'price_high_to_low' },
  { label: 'Recently listed', value: 'recently_listed' },
  { label: 'Recently sold', value: 'recently_sold' },
];

export const ORDER_TYPES = [{ label: 'Buy Now', value: 'buy_now' }];

export const MOONSAMA_MAX_SUPPLY = 1000;

export const MOONSAMA_TRAITS = {
  'Yellow Bird': 120,
  'Rainbow Shirt': 141,
  'No body accessory': 863,
  'Blue Hair': 37,
  'Bored Eyes': 213,
  'No hand accessory': 939,
  'No dimension': 994,
  'Purple Bird': 70,
  'Red Shirt': 157,
  'Aviator Hat': 13,
  'Yellow Geeky Glasses': 106,
  'Blue Bird': 153,
  'Green Shirt': 194,
  'Straight green': 41,
  'Black Geeky Glasses': 99,
  'Pink Bird': 117,
  'Blue Shirt': 176,
  'Happy Eyes': 238,
  'Cyan Bird': 152,
  'Orange Bufoon': 33,
  'Red Mohawk': 49,
  Cyclops: 34,
  'Green Bird': 127,
  Cigar: 128,
  'Blue Bufoon': 26,
  'No jacket': 137,
  'Blonde Hair': 36,
  'White Shades': 32,
  'Red Bird': 124,
  'Astronaut Helmet': 9,
  'Curious Eyes': 254,
  'Judo Outfit': 93,
  'Straight Red': 43,
  'Green Mohawk': 46,
  'No hat': 69,
  'Green Bufoon': 29,
  'Golden Bird': 19,
  'Sheriff Outfit': 80,
  'Black Cap': 39,
  'Black Bird': 55,
  'Samurai Top': 39,
  'Orange Cap': 45,
  'Grey Headset': 36,
  'Blue Mohawk': 45,
  'Black Mohawk': 59,
  'Blonde Mohawk': 42,
  'Blue Cap': 36,
  'Cheerleader Pom': 20,
  'Brown Cowboy': 23,
  'Detective Cap': 38,
  'Red Headset': 10,
  'Straight Black': 45,
  'Champion Gloves': 15,
  'White Bird': 63,
  'Straight Blonde': 38,
  'Black Shades': 24,
  'Hero Outfit': 22,
  'Pink Headset': 11,
  'Black Cowboy': 24,
  'Green Hair': 30,
  'Green Headset': 7,
  'Moonfinity Gauntlet': 9,
  'Boxing Gloves': 17,
  'Gold Chain': 9,
  Crown: 2,
  Neon: 6,
};

export const PONDSAMA_TRAITS = {
  'Yellow Bird': 120,
  'Rainbow Shirt': 141,
  'No body accessory': 863
};
